### ISSUE TITLE
Allow overwriting the window title

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [celluloid-player/celluloid#723] opened 2021-12-20 16:01 UTC
mpv allows setting the window title with `--title="Foo"`. This would be a nice feature in celluloid.

![image](https://user-images.githubusercontent.com/15961647/146796406-8053e66b-fe8a-4214-ad61-9d381e218635.png)

**Comment by gnome-mpv** [comment] 2021-12-20 21:39
Duplicate of #269

**Closed by gnome-mpv** 2021-12-20 21:39 UTC
Labels: enhancement
