### ISSUE TITLE
horizontal stripes on xorg

### ISSUE THREAD

**Issue by worldknote** [celluloid-player/celluloid#434] opened 2019-05-21 09:53 UTC
os: fedora silverblue 30
gnome 3.32.2. 

prozessor: intel core i5-8250U CPU @ 1.60GHz × 8 
graphics: intel UHD Graphics 620 (Kabylake GT2) / AMD Iceland

overview: since i have problems with wayland, xorg is running. if i play a video and there is a lot of movement, horizontal stripes appear. only under xorg, not on wayland. 

1. play a video with a lot of movements under xorg.

2. horizontal stripes appear

3. play a video with a lot of movements under wayland

4. the problem does not occur.

gnome mpv, version: 0.16, flatpak

is there a command for my external conf - file to fix this problem (or any other solution)?

**Comment by gnome-mpv** [comment] 2019-05-21 10:02
Duplicate of #232.

You can try disabling client-side decorations, or use [this gnome-shell extension](https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect).

**Closed by gnome-mpv** 2019-05-21 10:02 UTC
