### ISSUE TITLE
Wrong time in the seek bar

### ISSUE THREAD

**Issue by popov895** [celluloid-player/celluloid#662] opened 2021-05-31 15:51 UTC
Overview Description:

![celluloid](https://user-images.githubusercontent.com/24252473/120216196-5e8d9f80-c23f-11eb-8dfe-b793e7843794.png)

Tooltip shows incorrect time when hovering over the seek bar. Also, after clicking on the seek bar (guided by the time in the tooltip), the video jumps to the wrong position. The easiest way to reproduce this issue is to run Celluloid with the `--mpv-start` option.  Here's the log of Celluloid I ran with parameter `--mpv-start=00:30:00`:

[celluloid.zip](https://github.com/celluloid-player/celluloid/files/6571239/celluloid.zip)

Version:

OS: Fedora 34 Wayland/X11
Celluloid: 0.21 (celluloid-0.21-1.fc34 from rpmfusion-free)

**Comment by gnome-mpv** [comment] 2021-05-31 16:07
Duplicate of #651

**Closed by gnome-mpv** 2021-05-31 16:07 UTC
