### ISSUE TITLE
Celluloid crashes when KDE Connect is open

### ISSUE THREAD

**Issue by mariomadproductions** [celluloid-player/celluloid#808] opened 2022-09-21 21:46 UTC
Overview Description:
Celluloid crashes when KDE Connect is open.

Steps to Reproduce:
1. Install KDE Connect
2. Open KKDE Connect
3. Pair phone
4. Open Celluloid and open video/Have Celluloid already open with video open

Actual Results:
Celluloid crashes

Expected Results:
Celluloid does not crash

Version: 0.21

Additional Information:
KDE Connect v21.12.3

Terminal output
```
$ celluloid 
**
GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Bail out! GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Aborted (core dumped)
```

Thanks in advance

**Comment by gnome-mpv** [comment] 2022-09-22 00:57
Already fixed in >= v0.22.

**Comment by gnome-mpv** [comment] 2022-09-22 00:57
Duplicate of #688

**Closed by gnome-mpv** 2022-09-22 00:57 UTC

**Comment by mariomadproductions** [comment] 2022-09-22 01:37
Ah, thanks.
