### ISSUE TITLE
Celluloid 0.22 crashes when I try to play a video on Wayland session of KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#738] opened 2022-01-07 19:12 UTC
Overview Description:
Celluloid always crashes when I try to play a video on Arch Linux ruuning Wayland session of KDE Plasma.
Steps to Reproduce:
1. open Celluoid on Wayland session of KDE Plasma
2. open a video via '+' button
3.

Actual Results:
crash
Expected Results:
video plays
Version:
0.22 from Arch repos and celluloid-git from AUR
Additional Information:
output in terminal:
```
Gdk:ERROR:../gtk/gdk/wayland/gdksurface-wayland.c:2286:gdk_wayland_toplevel_inhibit_idle: assertion failed: (wayland_toplevel->idle_inhibitor && wayland_toplevel->idle_inhibitor_refcount > 0)
Bail out! Gdk:ERROR:../gtk/gdk/wayland/gdksurface-wayland.c:2286:gdk_wayland_toplevel_inhibit_idle: assertion failed: (wayland_toplevel->idle_inhibitor && wayland_toplevel->idle_inhibitor_refcount > 0)
Aborted (core dumped)

```

**Comment by gnome-mpv** [comment] 2022-01-08 06:09
This seems to be a bug in GTK. Calling gtk_application_inhibit() on Plasma Wayland always triggers a crash.

**Comment by brolyxxx** [comment] 2022-01-08 13:11
Hi, for what it's worth I can confirm the same error in Sway under Wayland in Arch Linux 5.15.12-arch1-1, so probably not a Plasma-specific GTK bug

`celluloid 0.22-1`
`mpv 1:0.34.1-1`
`sway 1:1.6.1-2`
`wayland 1.20.0-1`
`gtk4 1:4.6.0-1`

**Comment by rumpelsepp** [comment] 2022-01-16 08:55
Also happens on `sway version 1.8-dev-e1db1f82 `

**Comment by gnome-mpv** [comment] 2022-01-20 03:12
This has been fixed in the Git version of GTK. I'll bump the minimum GTK version when they make a new release.

**Closed** 2022-02-12 16:25 UTC
Labels: not our bug, crash
