### ISSUE TITLE
Isn't opening problem

### ISSUE THREAD

**Issue by PeterKW** [celluloid-player/celluloid#706] opened 2021-11-11 04:56 UTC
When I try and open Celluloid it opens for a second and then closes again. I think I may have some sort of configuration problem not working but I'm not quite sure how to go about figuring out what it is and how to fix it?

```
GLib-GIO:ERROR:../glib/gio/gdbusconnection.c:4220:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Bail out! GLib-GIO:ERROR:../glib/gio/gdbusconnection.c:4220:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
zsh: abort (core dumped)  celluloid
```

![image](https://user-images.githubusercontent.com/13779157/141239660-90167a6d-8d64-41c3-b994-0aa167533295.png)

**Comment by gnome-mpv** [comment] 2021-11-11 05:20
Are you using v0.22?

**Comment by PeterKW** [comment] 2021-11-11 05:34
From the Manjaro Repos I think using pamac:

![image](https://user-images.githubusercontent.com/13779157/141243270-9c4fc651-19b6-414b-be73-409fed772e15.png)

**Comment by gnome-mpv** [comment] 2021-11-11 05:45
Duplicate of #688

**Comment by gnome-mpv** [comment] 2021-11-11 05:46
The bug is already fixed in v0.22.

**Closed by gnome-mpv** 2021-11-11 05:46 UTC

**Comment by PeterKW** [comment] 2021-11-11 05:50
Ah okay, so I need to wait for Manjaro Repo owners to update?

**Comment by gnome-mpv** [comment] 2021-11-11 09:06
There are other ways to get the updated version, but it's probably best to just wait for your repo to update.

**Comment by OdinVex** [comment] 2022-08-08 16:02
Back on Mint 21 for me. https://github.com/celluloid-player/celluloid/issues/688#issuecomment-1208309684
