### ISSUE TITLE
Subtitles flicker on version 0.22

### ISSUE THREAD

**Issue by AmitGolden** [celluloid-player/celluloid#725] opened 2021-12-25 12:31 UTC
Overview Description:
When using subtitles, they flicker no matter the language, or the video. 
This started happening in version 0.22.
I'm using Qtile on X11.

Steps to Reproduce:
1. Open a video
2. Attach a subtitles file
3. Start playing

Actual Results:
The subtitles flicker.

Expected Results:
They should not flicker.

Version:
0.22

Additional Information:
Since version 0.22 and the migration to gtk4, my gtk theme is no longer applied, and the text is blurry.

**Comment by palob** [comment] 2021-12-25 15:50
This might not be a Celluloid or a mpv issue. IIRC there was a time when Celluloid didn't show flickering subtitles. An update of whatever dependency (didn't scrutinise which one yet)might have caused this.

Yeah, your GTK theme would have need to be rewritten for GTK4 and regarding the blurriness please cf.
https://gitlab.gnome.org/GNOME/gtk/-/issues/3787

**Comment by AmitGolden** [comment] 2021-12-25 16:02
I tried using plain mpv and it didn't have any problems.
Also I downgraded Celluloid to 0.21 and it works again.

Thanks for your help! :)

**Comment by gnome-mpv** [comment] 2021-12-25 16:44
I can't reproduce this. Tested with QTile 0.19.0 on X11.

What GPU are you using?

**Comment by palob** [comment] 2021-12-25 16:59
Intel Integrated HD 620 (Kaby Lake).

**Comment by msarkisian** [comment] 2022-01-01 11:59
Same issue with subtitles, and video also sometimes flickers (on larger files? unsure exactly where)
Likewise, these issues are unique to celluloid, and running naked mpv has no problems whatsoever.
Issues seen on both Gnome/Wayland and Xfce/X11.
Like the other guy, downgrading fixed the issues.
Intel CoffeeLake Integrated Graphics (630).

**Comment by diegovasconcelos** [comment] 2022-01-01 15:13
Same problem here with subtitles and video sometimes flickers.
Downgrading for 0.21 fixed the issues.

Fedora 35 - Wayland
Intel UHD Graphics 630
Celluloid Flatpak.

**Comment by Matthis-F** [comment] 2022-01-08 22:06
Same problem here, only when playing a large files with subtitles.

Arch - Wayland
Intel TigerLake-H GT1
Celluloid 0.22

**Comment by sceptri** [comment] 2022-01-09 10:12
Same problem here, subtitles and sometimes video flickers (more so on fullscreen). 
Playing with pure MPV is 100% okay.
Also, it happens only on the second display (2K monitor, both on 74.92Hz and 59.95 Hz)

openSUSE Tumbleweed
Mesa Intel® UHD Graphics 620 (WHL GT2)
Celluloid 0.22 installed via zypper

**Comment by gnome-mpv** [comment] 2022-01-10 04:53
Looks like the issue might be Intel-specific. I don't have access to a machine with Intel GPU right now so it's a bit difficult for me to debug.

**Comment by tim77** [comment] 2022-01-10 09:49
It's very likely Intel issue and not reproducible on Nvidia. Also other folks noticed that it appears first time after `bc355414cfd52e1d8e9070bde0fcc60acfc5851aac63d12f17f2591d03a3c288` commit (runtime update to v41).

**Comment by frnmz** [comment] 2022-01-17 03:41
It's actually a mesa regression that starting in version 21.3.
I've filled a bug report both in mpv github and mesa gitlab:
https://github.com/mpv-player/mpv/issues/9579
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5744

The flickers is gone now in mpv, but strangely still happens on celluloid.
That's why i think it's now celluloid specific.
Should I open a new issue related to this?

**Comment by gnome-mpv** [comment] 2022-01-17 04:20
>  Should I open a new issue related to this?

We can keep using this issue.

**Comment by frnmz** [comment] 2022-02-01 23:57
This issue seems fixed in the latest mesa (21.3.5) on Fedora 35.
Can any others confirm?

**Comment by palob** [comment] 2022-02-02 01:07
Yay, it's gone :tada:

**Closed** 2022-02-02 06:53 UTC
Labels: not our bug
