### ISSUE TITLE
Playlist button wrongly labelled as "Toggle Fullscreen"

### ISSUE THREAD

**Issue by mayhair** [celluloid-player/celluloid#912] opened 2023-12-20 11:13 UTC
Overview Description:
When hovering the cursor over the playlist toggle button, "Toggle Fullscreen" shows.

Steps to Reproduce:
1. Open any media file.
2. Hover the cursor over the button which toggles the visibility of the playlist.

Actual Results:
The tooltip "Toggle Fullscreen" is shown.

Expected Results:
A more fitting indicator, such as "Toggle Playlist".

Version:
0.26

Additional Information:
I'm using the Void Linux package, not Flatpak or anything else.

[Screencast from 2023-12-20 16-12-29.webm](https://github.com/celluloid-player/celluloid/assets/21954283/58948ed1-ebba-41e2-841d-bba6965c198c)

**Comment by gnome-mpv** [comment] 2023-12-20 12:45
Already fixed in b87a88df6699527e7054ae0e831d290b8090698c.

**Comment by gnome-mpv** [comment] 2023-12-20 12:46
Duplicate of #896

**Closed by gnome-mpv** 2023-12-20 12:45 UTC
