### ISSUE TITLE
Show resolution/bitrate when video track has no name

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [celluloid-player/celluloid#722] opened 2021-12-20 15:46 UTC
Currently, if a video track has no title, it just shows up as "Unknown". This makes video track selection for HLS streams with multiple resolution and bitrate options difficult. It would be more useful to display the resolutions and/or bitrate instead.

![image](https://user-images.githubusercontent.com/15961647/146793213-117a849b-eaa0-4c6d-ba17-adf82b394724.png)

ffprobe output:
```
  Duration: 00:10:02.00, start: 2.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 1287744
  Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 1287744
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
  Program 1 
    Metadata:
      variant_bitrate : 434374
  Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 480x270 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 434374
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
  Program 2 
    Metadata:
      variant_bitrate : 722089
  Stream #0:2: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 512x288 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 722089
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
  Program 3 
    Metadata:
      variant_bitrate : 2148032
  Stream #0:3: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 960x540 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 2148032
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
  Program 4 
    Metadata:
      variant_bitrate : 3978550
  Stream #0:4: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 3978550
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
  Program 5 
    Metadata:
      variant_bitrate : 6611453
  Stream #0:5: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 6611453
  Stream #0:6(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, 98 kb/s (default)
    Metadata:
      id3v2_priv.com.elementaltechnologies.timestamp.utc: 2021-05-14T00:00:00Z
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x02\xbf 
      comment         : English
```

If you point me in the right direction, I'd be willing to implement the change.

**Comment by gnome-mpv** [comment] 2021-12-20 21:22
Duplicate of #373

**Comment by gnome-mpv** [comment] 2021-12-20 21:23
>If you point me in the right direction, I'd be willing to implement the change.

See my response in #373.

**Closed by gnome-mpv** 2021-12-20 21:23 UTC
