### ISSUE TITLE
Slider time control

### ISSUE THREAD

**Issue by maxchendt** [celluloid-player/celluloid#678] opened 2021-07-30 10:48 UTC
Overview Description: wrong time tip on slider

Steps to Reproduce:
1. play a video, and try to adjust the time by mouse

Actual Results: the time tip is not the same as current time indicated

Expected Results: sync time

Version: 0.21

Additional Information:  screenshot shows that the slider time is `00:26:48` but the real time play is `00:25:39`
![Screenshot from 2021-07-30 18-30-52](https://user-images.githubusercontent.com/9275768/127642044-70765349-ce26-4cc2-bba0-2b5957db0367.png)

**Comment by gnome-mpv** [comment] 2021-07-30 11:23
Duplicate of #651

**Closed by gnome-mpv** 2021-07-30 11:23 UTC
