### ISSUE TITLE
Feature reqeust, delete file from drive option.

### ISSUE THREAD

**Issue by anonymoustly** [celluloid-player/celluloid#648] opened 2021-03-26 23:58 UTC
Option to delete permanently from drive.

**Comment by gnome-mpv** [comment] 2021-03-27 09:03
Duplicate of #558

In addition to the solution in #558, there's also [a script](https://github.com/zenyd/mpv-scripts#delete-file) for deleting multiple files at once.

**Closed by gnome-mpv** 2021-03-27 09:03 UTC

**Comment by gnome-mpv** [comment] 2021-03-27 09:06
Duplicate of #558
