### ISSUE TITLE
It crashes on Manjaro.

### ISSUE THREAD

**Issue by laichiaheng** [celluloid-player/celluloid#485] opened 2019-10-31 15:13 UTC
- Overview Description:
It crashes.
- Steps to Reproduce:
1. Play video
2. Click the button
![2019-10-31 23-11-02 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/67959543-e2327500-fc33-11e9-98b7-1591a3df5d56.png)
- Actual Results:
It crahses.
- Expected Results:
Show something.
- Version:
0.17
- Additional Information:
```
#0  0x00007ffff5211e0e in  () at /usr/lib/libmpv.so.1
#1  0x00007ffff521bd43 in  () at /usr/lib/libmpv.so.1
#2  0x00007ffff51f7b78 in  () at /usr/lib/libmpv.so.1
#3  0x00007ffff522f13a in  () at /usr/lib/libmpv.so.1
#4  0x00007ffff52314dd in  () at /usr/lib/libmpv.so.1
#5  0x00007ffff5228209 in  () at /usr/lib/libmpv.so.1
#6  0x00007ffff52286fa in  () at /usr/lib/libmpv.so.1
#7  0x00007ffff520eb21 in  () at /usr/lib/libmpv.so.1
#8  0x00007ffff48504cf in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff7eb92d3 in clone () at /usr/lib/libc.so.6
```

**Comment by gnome-mpv** [comment] 2019-10-31 16:04
Duplicate of #480

**Closed by gnome-mpv** 2019-10-31 16:04 UTC
