### ISSUE TITLE
Window decorations/widgets not rendering properly after exiting full-screen mode

### ISSUE THREAD

**Issue by KSXGitHub** [celluloid-player/celluloid#779] opened 2022-05-28 08:01 UTC
**[Demo Video](https://youtu.be/M2kan8_kWAk)**

Steps to Reproduce:
1. Open an MKV video
2. Activate and deactivate full-screen mode multiple times (by pressing <kbd>F</kbd>) until some window widgets disappear.

Actual Results:
Some window widgets are not rendered properly.

Expected Results:
Everything is rendered properly

Versions:
* celluloid 0.23
* mpv 0.34.1
* gtk4 4.6.4
* gnome-shell 42.1

Additional Information:
* Desktop Session: GNOME (Xorg)
* OS: Arch Linux
* Clapper also has this issue, ~~but it fixes itself after 1 sec, so it's not a big problem.~~
* GNOME Videos does not have this problem at all. Entering/exiting full-screen is smooth and without issue.

**Comment by gnome-mpv** [comment] 2022-05-30 14:50
Duplicate of #746

**Closed** 2022-05-30 14:50 UTC
