### ISSUE TITLE
Celluloid freezing and crashing when opening.

### ISSUE THREAD

**Issue by catto24** [celluloid-player/celluloid#866] opened 2023-06-14 23:14 UTC
Overview Description:
Celluloid will freeze and crash when opening, whether it's just opening the app or playing a file.

Steps to Reproduce:
1. Open Celluloid.

Actual Results:
Freezes for around 10 seconds and crashes.

Expected Results:
Opens.

Version:
0.20 DEB, pre-installed with OS.

Additional Information:
Running Ubuntu Budgie 22.04.2 LTS.
Rhythmbox does not have this problem.

**Comment by gnome-mpv** [comment] 2023-06-15 01:23
I can't reproduce this.

If you start Celluloid from the command line, do you see any error messages?

**Comment by catto24** [comment] 2023-06-15 05:12
`catto24@catto24-lick:~$ celluloid
**
GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Bail out! GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Aborted (core dumped)
catto24@catto24-lick:~$ `

**Comment by gnome-mpv** [comment] 2023-06-15 06:07
This is an old bug that's triggered by KDE Connect.

Upgrading to v0.22 or newer will fix the problem. You can use [this PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv) to upgrade.

**Comment by gnome-mpv** [comment] 2023-06-15 06:08
Duplicate of #688

**Closed by gnome-mpv** 2023-06-15 06:08 UTC

**Comment by catto24** [comment] 2023-06-15 06:44
ah kk
