### ISSUE TITLE
Error: Playback was terminated abnormally. Reason: Loading Failed.

### ISSUE THREAD

**Issue by spectrumcomputing** [celluloid-player/celluloid#463] opened 2019-08-28 20:26 UTC
Overview Description:

When I try and play video file from a network attached storage device I get an error

Steps to Reproduce:
1. Right click on video on NAS
2. Choose 'Open with Celluloid'
3.Error occurs

Actual Results:
Error: Playback was terminated abnormally. Reason: Loading Failed.

Expected Results:
Play Video

Version: 0.17

Additional Information:
Ubuntu 19.04 Desktop
I don't recall this being an issue in earlier versions.  I'm assuming this is a celluloid issue as I can right click and play in Chrome or VLC without an issue.

**Comment by gnome-mpv** [comment] 2019-08-29 15:04
Are you using the Flatpak version?

**Comment by spectrumcomputing** [comment] 2019-08-29 16:26
Hi, yes I am. Sorry, I should have mentioned that!

I'm using that because the PPA does not seem to have been updated for a while.  Cheers

**Comment by gnome-mpv** [comment] 2019-08-29 16:40
Right now, if you want to access network mounts with the Flatpak version, you need to explicitly allow Celluloid to access GVFS. See @saivert's comment in #396 (replace `io.github.GnomeMpv` with `io.github.celluloid_player.Celluloid`).

**Comment by gnome-mpv** [comment] 2019-08-29 16:40
Duplicate of #396.

**Closed by gnome-mpv** 2019-08-29 16:40 UTC

**Comment by spectrumcomputing** [comment] 2019-08-29 16:48
Thanks, I have raised a request for the PPA to be updated. Thanks for your work on this. Its a great app!
