### ISSUE TITLE
Crash when clicking on UI since upgrade to Fedora 31

### ISSUE THREAD

**Issue by didierga** [celluloid-player/celluloid#471] opened 2019-09-20 10:21 UTC
Overview Description:
Since upgrade to Fedora 31 Celluloid crashes with segment fault when clicking at least on hamburger menu or on progress bar

Steps to Reproduce:
1. Upgrade to or install Fedora 31
2. Try to use Celluloid

Actual Results:
Crash with segment fault

Expected Results:
As with Fedora 30, a nice player

Version:
celluloid-0.17-1.fc31.x86_64
mpv-0.29.1-10.20190814.gitcd7bcb9.fc31.x86_64
mpv-libs-0.29.1-10.20190814.gitcd7bcb9.fc31.x86_64
mpv-libs-devel-0.29.1-10.20190814.gitcd7bcb9.fc31.x86_64

Additional Information:

**Comment by didierga** [comment] 2019-09-20 10:24
[celluloid_crash.txt](https://github.com/celluloid-player/celluloid/files/3635441/celluloid_crash.txt)

**Comment by gnome-mpv** [comment] 2019-09-20 15:00
Duplicate of #468

**Closed** 2019-09-20 15:01 UTC
