### ISSUE TITLE
Problem with keybindings (input.conf) using keys of numeric keyboard

### ISSUE THREAD

**Issue by simonbcn** [celluloid-player/celluloid#428] opened 2019-05-01 14:32 UTC
```
Arch Linux 
GNOME Shell 3.32.1 on Wayland
GNOME MPV 0.16
```
I have defined the next `input.conf`:
```
q quit_watch_later
ESC quit_watch_later
RIGHT seek 5
LEFT seek -7
UP add volume 2
DOWN add volume -2
PGUP seek -40
PGDWN seek 60
- add video-zoom -0.3                     
+ add video-zoom +0.3 
```

But when I press `+` or `-` in numeric keypad, gnome-mpv shows an error on console and it doesn't zoom in/out:
```
** (gnome-mpv:9227): WARNING **: 16:27:20.873: Failed to run mpv command "keydown KP_Subtract". Reason: error running command.
** (gnome-mpv:9227): WARNING **: 16:27:20.887: Failed to run mpv command "keyup KP_Subtract". Reason: error running command.
** (gnome-mpv:9227): WARNING **: 16:27:22.007: Failed to run mpv command "keydown KP_Add". Reason: error running command.
** (gnome-mpv:9227): WARNING **: 16:27:22.087: Failed to run mpv command "keyup KP_Add". Reason: error running command.
```
It works if I press `+` or `-` in _normal_ keyboard.
In `mpv` this works with both keys.

I've added the next lines to input.conf:
```
KP_Subtract add video-zoom -0.3
KP_Add add video-zoom +0.3
```
But with the same result: error and it does nothing.

**Comment by gnome-mpv** [comment] 2019-05-01 14:41
Duplicate of #421

This has already been fixed in 58fbcb7 and 26a8ec7. The fix will be included in the next release.

**Closed by gnome-mpv** 2019-05-01 14:41 UTC
