### ISSUE TITLE
save-position-on-quit doesn't work

### ISSUE THREAD

**Issue by Rrauros** [celluloid-player/celluloid#941] opened 2024-04-22 18:48 UTC
Overview Description: --save-position-on-quit doesn't work. It doesn't work when putting it into config file or it doesn't work whene putting to extra mpv option.

Steps to Reproduce:
1.Put --save-position-on-quit to extra mpv option.
2.Close a video.
3.Reopen it to see its start from beginning.

Actual Results:

Expected Results: It should save the last position.

Version: Using the flatpak version. 

Additional Information: I can see that its creating files in io.github.celluloid_player.Celluloid/config/celluloid/watch_later but that doesn't seems to be doing anything. Usually that happens with mpv when app closed unexpectedly. I assume this is what's happening here as well? My other configurations seems to be working (sharpen, sub-scale, cache etc.)

**Comment by gnome-mpv** [comment] 2024-04-23 19:48
Duplicate of #529

**Closed** 2024-04-23 19:48 UTC
