### ISSUE TITLE
celluloid crashes on Menu -> Open -> sort by Modified

### ISSUE THREAD

**Issue by technojoe** [celluloid-player/celluloid#751] opened 2022-02-18 01:25 UTC
Overview Description: celluloid crashes when sorting files by Modified from the Open dialog.

Steps to Reproduce:
1. Open Celluloid
2. Click the Plus in the upper left.
3. Click Open.
4. Click the Modified in the dialog box.

Actual Results:
crash

Expected Results:
Files in directory sorted by Modified

Version:
0.22

Additional Information:
I believe this is a regression from 0.21, but I cannot be sure. I am just now getting around to reporting it.

I do not have NVIDIA hardware.

== abrt ==
reason: celluloid killed by SIGSEGV
crash_function: gtk_tree_view_update_rubber_band_selection_range.constprop.0
cmdline: /usr/bin/celluloid --gapplication-service
executable: /usr/bin/celluloid
package: celluloid-0.22-3.fc35
component: celluloid
pid: 325008
type/analyzer: CCpp/abrt-journal-core
pkg_fingerprint: E06F 8ECD D651 FF2E
dso_list: /usr/bin/celluloid celluloid-0.22-3.fc35.x86_64 (RPM Fusion) 1639866791
rootdir: /
kernel: 5.16.8-200.fc35.x86_64
pkg_vendor: RPM Fusion
run_level: N 5
os_release: Fedora release 35 (Thirty Five)
journald_cursor: s=c05c8feebd764d089afd16696679ff1f;i=4c6e7;b=9309c1b3333e49f6882f602c5db7fac3;m=de67bd776;t=5d8401b02e12c;x=b745399efcdacd80
cgroup: 0::/user.slice/user-1000.slice/user@1000.service/app.slice/dbus-:1.2-io.github.celluloid_player.Celluloid@3.service
uuid: 90263dca83b662909ffe2926ecc5f466f65185a5
abrt_version: 2.14.6
architecture: x86_64
ureports_counter: 1
data_directory: /var/spool/abrt/ccpp-2022-02-17-16:38:46.717883-325008
core_dump: $DATA_DIRECTORY/coredump (binary file, 536.7 MiB)

--Feb 17 16:36:47 localhost.localdomain celluloid[324678]: Cannot load libcuda.so.1
Feb 17 16:37:09 localhost.localdomain celluloid[324678]: _gtk_tree_path_new_from_rbtree: assertion 'node != NULL' failed
Feb 17 16:37:09 localhost.localdomain celluloid[324678]: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed
Feb 17 16:38:20 localhost.localdomain celluloid[324857]: Cannot load libcuda.so.1
Feb 17 16:38:28 localhost.localdomain celluloid[324857]: _gtk_tree_path_new_from_rbtree: assertion 'node != NULL' failed
Feb 17 16:38:28 localhost.localdomain celluloid[324857]: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed
Feb 17 16:38:36 localhost.localdomain celluloid[325008]: Cannot load libcuda.so.1
Feb 17 16:38:45 localhost.localdomain celluloid[325008]: _gtk_tree_path_new_from_rbtree: assertion 'node != NULL' failed
Feb 17 16:38:45 localhost.localdomain celluloid[325008]: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed

**Comment by technojoe** [comment] 2022-02-18 01:26
[backtrace.txt.gz](https://github.com/celluloid-player/celluloid/files/8093386/backtrace.txt.gz)

**Comment by gnome-mpv** [comment] 2022-02-18 09:14
Sounds like the same issue as #712.

**Comment by technojoe** [comment] 2022-02-18 09:39
Thanks. Sorry I didn't see that. I really looked.

1) Has a bug report been filed upstream with GTK?

2) When will this be pushed to a new release so package maintainers can pick it up?

**Comment by gnome-mpv** [comment] 2022-02-18 09:59
> Has a bug report been filed upstream with GTK?

Not to my knowledge. Feel free to file one with GTK.

> When will this be pushed to a new release so package maintainers can pick it up?

I hope to make a new release in a month or so. The [patch](https://github.com/celluloid-player/celluloid/commit/4592648b088dc79f32fcfe5c78f7a7687b599c1f.patch) is pretty small though, so it wouldn't be too difficult apply to a package.

**Comment by technojoe** [comment] 2022-02-19 11:30
>> Has a bug report been filed upstream with GTK?

> Not to my knowledge. Feel free to file one with GTK.

So the end-user who is not familiar with your project, nor GTK, is supposed to file the bug report about your project with GTK? Got it. [https://gitlab.gnome.org/GNOME/gtk/-/issues/4708](https://gitlab.gnome.org/GNOME/gtk/-/issues/4708)

**Comment by gnome-mpv** [comment] 2022-02-19 14:43
>So the end-user who is not familiar with your project, nor GTK, is supposed to file the bug report about your project with GTK? Got it. https://gitlab.gnome.org/GNOME/gtk/-/issues/4708

Thanks for filing the bug report, but there's no need to get passive-aggressive. If you didn't want to file the report, you could have just said so.

**Comment by gnome-mpv** [comment] 2022-02-19 14:43
Duplicate of #712

**Closed** 2022-02-19 14:49 UTC
Labels: not our bug

**Comment by technojoe** [comment] 2022-02-20 23:06
I received this response:


> The reason why not calling set_select_multiple(True) "fixes" the issue is because selection rubber-banding in the TreeView is enabled if multiple selection is also enabled, and rubber-banding is broken because of a gesture conflict.

I hope this makes sense to you.
