### ISSUE TITLE
request: adjust window geometry during non-video playbak

### ISSUE THREAD

**Issue by brainchild0** [celluloid-player/celluloid#671] opened 2021-06-19 02:10 UTC
Presently, the window geometry and layout is the same when playing audio media, as compared to when playing video media, with any  thumbnail, if available,  displayed in the video pane, otherwise only the blank background color. If window resizing is disabled in the user settings, then the window size is preserved not only for video media of all resolutions, but also for for audio media.

Requested is a distinct window layout for audio media, which may be assumed whenever  audio media is playing. The earlier window layout would be restored when video media is  played. The new  layout would have fixed size, with a small region for a thumbnail, if available, and the window would not be resized dynamically according to the resolution of the available thumbnail. The new layout would be one specifically appropriate for playing media that have no video.

**Comment by gnome-mpv** [comment] 2021-06-19 08:36
Duplicate of #439

**Closed by gnome-mpv** 2021-06-19 08:36 UTC
